export const APP_LOADED = "APP_LOADED",
  SET_COLOR_SCHEME = "SET_COLOR_SCHEME";

export type ActionsType = "APP_LOADED" | "SET_COLOR_SCHEME";

export const SET_CHATS = "SET_CHATS",
  ADD_CHAT = "ADD_CHAT";

export type ChatType = "SET_CHATS" | "ASS_CHATS";

export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER",
  SET_PIN = "SET_PIN",
  SET_PASSWORD = "SET_PASSWORD";

export type FormEnumType = "SET_PHONE_NUMBER" | "SET_PIN" | "SET_PASSWORD";

export const SET_USER_DETAILS = "SET_USER_DETAILS",
  SET_USER_TOKEN = "SET_USER_TOKEN",
  SET_USER_ASSETS = "SET_USER_ASSETS",
  SET_USER_PROJECTS = "SET_USER_PROJECTS",
  SET_USER_TRANSACTIONS = "SET_USER_TRANSACTIONS",
  SET_USER_LINEAR_REFERRALS = "SET_USER_LINEAR_REFERRALS",
  SET_USER_GENERATION_REFERRALS = "SET_USER_GENERATION_REFERRALS",
  SET_USER_BALANCE = "SET_USER_BALANCE",
  RESET_USER_CONTEXT = "RESET_USER_CONTEXT";

export type UserType =
  | "SET_USER_DETAILS"
  | "SET_USER_TOKEN"
  | "RESET_USER_CONTEXT"
  | "SET_USER_ASSETS"
  | "SET_USER_PROJECTS"
  | "SET_USER_TRANSACTIONS"
  | "SET_USER_LINEAR_REFERRALS"
  | "SET_USER_GENERATION_REFERRALS"
  | "SET_USER_BALANCE";

export const SET_USER_LOCATION = "SET_USER_LOCATION";

export type NavigationType = "SET_USER_LOCATION";
